-- require("nvim-tree").setup({
--   sort_by = "case_sensitive",
--   view = {
--     width = 30,
--   },
--   renderer = {
--     group_empty = true,
--   },
--   filters = {
--     dotfiles = true,
--   },
--   disable_netrw       = true,
--   hijack_netrw        = true,
--   open_on_tab         = false,
--   hijack_cursor       = false,
--   update_cwd          = false,
--   diagnostics = {
--     enable = false,
--     icons = {
--       hint = '',
--       info = '',
--       warning = '',
--       error = '',
--     }
--   },
--   actions = {
--     open_file = {
--       quit_on_open = true,
--     },
--   },
--   update_focused_file = {
--     enable      = false,
--     update_cwd  = false,
--     ignore_list = {}
--   },
--   system_open = {
--     cmd  = nil,
--     args = {}
--   }
-- })
