#! /bin/sh

chosen=$(printf "  Power Off\n  Restart\n  Suspend\n  Lock" | rofi -dmenu -i -theme-str '@import "~/.local/share/rofi/themes/spotlight-dark.rasi"')

case "$chosen" in
	"  Power Off") poweroff ;;
	"  Restart") reboot ;;
	"  Suspend") systemctl suspend;;
	"  Lock") i3lock -c 000000;;
	*) exit 1 ;;
esac
